### ISSUE TITLE
Implement support for stochastic control flow (e.g. if and unbounded loop)

### ISSUE THREAD

**Issue by yebai** [TuringLang/Libtask.jl#96] opened 2021-12-12 20:48 UTC
Related https://github.com/TuringLang/AdvancedPS.jl/issues/37

**Comment by KDr2** [comment] 2022-01-27 23:59
Is it fine to close this issue and https://github.com/TuringLang/AdvancedPS.jl/issues/37 now?

**Comment by yebai** [comment] 2022-01-28 10:13
@KDr2 there is still one broken test for constrol flows, can you take a look? 

https://github.com/TuringLang/Turing.jl/pull/1766/files#diff-995baae0024148e101534255397cc34116f06aabbba2efc91d44e59bddb88b48R55

**Comment by KDr2** [comment] 2022-01-28 11:50
I haven't found the cause yet. Does this run well if it is called directly without Libtask.CTask?

The code below may contain some clues useful:

```
62:
  %183 = Core.isdefined(%6, :contents)
  br 63 unless %183
  br 64
63:
  br 64
64:
  %184 = Core.getfield(%6, :contents)
  %185 = Base.getindex(%184, %22)
  %186 = Base.getindex(%144, %185)  # !!! <-------- Here, %144 is a 1-element vector, %185 is 2
  %187 = Main.Normal(%186, 1.0)
  %188 = (DynamicPPL.check_tilde_rhs)(%187)
  %189 = (Base.maybeview)(%21, %22)
  %190 = (DynamicPPL.tilde_observe!!)(%4, %188, %189, %150, %145)
  %191 = Base.indexed_iterate(%190, 1)
  %192 = Core.getfield(%191, 1)
  %193 = Core.getfield(%191, 2)
  %194 = Base.indexed_iterate(%190, 2, %193)
  %195 = Core.getfield(%194, 1)
  br 65 (%195, %21)
65: (%196, %197)
  %198 = Base.iterate(%14, %23)
  %199 = %198 === nothing
  %200 = Base.not_int(%199)
  br 66 (%196) unless %200
  br 2 (%198, %196, %144, %197)
66: (%201)
  %202 = Core.tuple(nothing, %201)
  return %202

```

**Comment by yebai** [comment] 2022-01-30 16:50
@KDr2 I did some further debugging. The bug seems caused by `TArray`. Here are two examples using `TArray` and `Array` (deep copy enabled) respectively, the one with `Array` runs correctly. 


<details>
  <summary>`Array` with deep copy enabled for `TapedFunction`  </summary>

```julia
julia> using Turing, Libtask, Random, Test, DynamicPPL, Turing.RandomMeasures

julia> tape_copy(x::Array) = deepcopy(x)
tape_copy (generic function with 1 method)

julia> @model infiniteGMM(x) = begin
            # Hyper-parameters, i.e. concentration parameter and parameters of H.
            α = 1.0
            μ0 = 0.0
            σ0 = 1.0
            
            # Define random measure, e.g. Dirichlet process.
            rpm = DirichletProcess(α)
            
            # Define the base distribution, i.e. expected value of the Dirichlet process.
            H = Normal(μ0, σ0)
            
            # Latent assignment.
            z = zeros(Int, length(x))
                
            # Locations of the infinitely many clusters.
            μ = zeros(Float64, 0)
            
            for i in 1:length(x)
                
                # Number of clusters.
                K = maximum(z)
                nk = Vector{Int}(map(k -> sum(z .== k), 1:K))
        
                # Draw the latent assignment.
                z[i] ~ ChineseRestaurantProcess(rpm, nk)
                
                # Create a new cluster?
                if z[i] > K
                    push!(μ, 0.0)
        
                    # Draw location of new cluster.
                    μ[z[i]] ~ H
                end
                        
                # Draw observation.
                # println("z[$(i)]=", z[i], ", length(μ)=", length(μ));
                x[i] ~ Normal(μ[z[i]], 1.0)
            end
        end
infiniteGMM (generic function with 2 methods)

julia> # Generate some test data.
        Random.seed!(1);

julia> data = vcat(randn(10), randn(10) .- 5, randn(10) .+ 10);

julia> data .-= mean(data);

julia> data /= std(data);

julia> # MCMC sampling
        Random.seed!(2);

julia> iterations = 500;

julia> model_fun = infiniteGMM(data);

julia> empty!(Libtask.TRCache)
LRU{Any, Any}(; maxsize = 10)

julia> chain = sample(model_fun, SMC(), iterations);

```
</details>

<details>
  <summary>`TArray` example </summary>

```julia

julia> using Turing, Libtask, Random, Test, DynamicPPL, Turing.RandomMeasures

julia> @model infiniteGMM(x) = begin
            # Hyper-parameters, i.e. concentration parameter and parameters of H.
            α = 1.0
            μ0 = 0.0
            σ0 = 1.0
            
            # Define random measure, e.g. Dirichlet process.
            rpm = DirichletProcess(α)
            
            # Define the base distribution, i.e. expected value of the Dirichlet process.
            H = Normal(μ0, σ0)
            
            # Latent assignment.
            z = tzeros(Int, length(x))
                
            # Locations of the infinitely many clusters.
            μ = tzeros(Float64, 0)
            
            for i in 1:length(x)
                
                # Number of clusters.
                K = maximum(z)
                nk = Vector{Int}(map(k -> sum(z .== k), 1:K))
        
                # Draw the latent assignment.
                z[i] ~ ChineseRestaurantProcess(rpm, nk)
                
                # Create a new cluster?
                if z[i] > K
                    push!(μ, 0.0)
        
                    # Draw location of new cluster.
                    μ[z[i]] ~ H
                end
                        
                # Draw observation.
                # println("z[$(i)]=", z[i], ", length(μ)=", length(μ));
                x[i] ~ Normal(μ[z[i]], 1.0)
            end
        end
infiniteGMM (generic function with 2 methods)

julia> # Generate some test data.
        Random.seed!(1);

julia> data = vcat(randn(10), randn(10) .- 5, randn(10) .+ 10);

julia> data .-= mean(data);

julia> data /= std(data);

julia> # MCMC sampling
        Random.seed!(2);

julia> iterations = 500;

julia> model_fun = infiniteGMM(data);

julia> empty!(Libtask.TRCache)
LRU{Any, Any}(; maxsize = 10)

julia> chain = sample(model_fun, SMC(), iterations);

```
</details>

**Comment by KDr2** [comment] 2022-01-31 01:37
I went through all the instructions on the tape, found only these functions are called on `TArray`:

```
getindex
maximum
push!
setfield!
Setfield.set
```

And I tested them, all work well.
But I'm sorry that I might have no time to do further investigation on this before my holiday ends.

**Comment by yebai** [comment] 2022-01-31 07:59
No worries @KDr2 - Happy Chinese New Year!

**Comment by KDr2** [comment] 2022-02-01 09:12
I found if we don't copy `TArray` at all, the error will disappear. The provided code contains some macro expansions which are complicated, I wonder if we can constructor a much simpler case to reproduce the error.

**Closed** 2022-02-08 16:40 UTC
